name: "Compile Taffy"
on: [push]
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup JDK 21"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - run: mvn --batch-mode --update-snapshots verify
      - run: cp target/*-jar-with-dependencies.jar dist/taffy.jar
      - uses: actions/upload-artifact@v4
        with:
          name: "Taffy rolling release"
          path: dist
